library 'practise-library'

pipeline {
    agent any
    stages {
        stage ('Test Libaray') {
            steps {
                practise5('Practise')
                practise5('Jenkins')
                practise5('Kumar')
            }
        }
    }
}

