pipeline {
    agent any
    stages {
        stage ("Request website") {
            steps {
                script {
                    response_code = sh(
                        script: "curl -o /dev/null -s -w %{http_code} www.example.com",
                        returnStdout: true
                    ).toInteger()

                    echo "${response_code}"
                }
            }
        }  
        stage ("Check Http Code") {
            steps {
                script {
                    if( response_code != 200 ) {
                        sh "false"
                    }
                }
            }
        }
    }
     /*
        post: 在 Stage 結束時而外執行的步驟，會根據最後一次結果來判斷
        官方文件：https://www.jenkins.io/doc/book/pipeline/syntax/
    */
    post {
        success {
            echo "Success"
        }
        failure {
            withCredentials([string(credentialsId: 'telegram-bot', variable: 'TELEGRAM_TOKEN')]) {
                withCredentials([string(credentialsId: 'telegram-notification-group', variable: 'TELEGRAM_GROUP_ID')]) {
                    sh '''
                        message="${CHECK_DOMAIN} response code != 200."
                        curl -X GET "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
                            -d "chat_id=${TELEGRAM_GROUP_ID}&text=${message}"
                    '''
                }
            }
        }
    }
}