pipeline {
    agent any
    environment {
        K6_SCRIPT="${WORKSPACE}/pipeline-scripts/practise-7/k6-test.js"
    }
    stages {
        stage ("Run K6 Test") {
            steps {
                sh "k6 run ${K6_SCRIPT}"
            }
        }
    }
    post {
        always {
            /*
                Jenkins CSP Policy: https://www.jenkins.io/doc/book/security/configuring-content-security-policy/
                Jenkins archive: https://www.jenkins.io/doc/pipeline/steps/core/
            */
            archiveArtifacts artifacts: 'practise7.html',
            followSymlinks: true
        }
    }
}