pipeline {
    //不指定 Jenkins agent
    agent any
    //Pipeline 執行步驟
    stages {
        //Pipeline 其中一個步驟
        stage ('First Pipeline') {
            steps { //宣告行為
                echo 'Hello Word'
            }
        }
    }
}